### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by NoLooseEnds** [pawelmalak/flame#14]
Would it be possible with some sort of API, that you can add labels to your docker-compose files and automatically populate Flames dashboard?

**Comment by pawelmalak** [comment]
Hi. As I said before this is my first time using Docker in any project so I don't know if it would be possible to implement. Do you know any other project that implements that kind of functionality so I could take a closer look at it? 

Right now, flame exposes RESTful API for apps, categories and bookmarks if that's what you mean.

**Comment by NoLooseEnds** [comment]
[Traefik](https://doc.traefik.io/traefik/providers/docker/) maybe? I think you need to expose the docker.socket, but I'm no developer, so not sure.

**Comment by pawelmalak** [comment]
Sorry, but for now implementation of this feature is out of my skill and knowlage range.

**Comment by NoLooseEnds** [comment]
That you leave it open, so that other devs maybe can help if they see it and it's something they know how to do. 
Mark it with `help wanted` for instance and maybe add it to a milestone if it's a feature you like. :)

Like this:
<img width="506" alt="Screenshot 2021-06-09 at 22 58 19" src="https://user-images.githubusercontent.com/4103531/121428520-30fad180-c976-11eb-8539-6817883e4410.png">

**Comment by rgriffogoes** [comment]
I'm in a search for such feature, but I guess the popular dashboards options also don't have it.  Currently I'm investigating what would be the best option, and I guess Flame seems to be a good candidate (API already there).

And instead of trying to consume docker api (like Portainer and Traefik does), I was even thinking about consuming Traefik api (rawdata) -- that way it would be possible to generate apps even for non-docker things, and the whole "url/pathprefix" problem would be already solved.

So the problem is divided in different parts, and a final solution could be a mix of any:

Data acquisition:
1. Read docker socket for special labels
2. Consume Traefik api

Feature placement:
1. Simple script to be called/croned
2. Independent simple app (with timed checks, listener on socket, webapi to be hooked)
3. Feature in Dashboard code

Target Dashboard:
1. Flame (rest api)
2. Homer (static file generation)
3. Heimdall (no idea)
4. Organizr (no idea)

I've been using Organizr for a few years already, but the other dashboards I installed just recently.

**Comment by jjack** [comment]
> Would it be possible with some sort of API, that you can add labels to your docker-compose files and automatically populate Flames dashboard?

I'm not sure how much Flame would be able to automatically populate with just labels and nothing else exposed/consumable.

If you were to label a container as being flammable, Flame would then need some way of determining the type, category, name, url, and icon for it. Many of those would be awfully hard (if not impossible) to divine on their own, so you'd also need to use labels to define the values.

eg:
```
labels:
  - flame.type=application
  - flame.category=downloads
  - flame.name=Downloader 3000
  - flame.url=http://localhost:3000
  - flame.icon=icon-name
```

And at that point, you're pretty much just making a distributed configuration file for Flame.

**Comment by NoLooseEnds** [comment]
Dunno. Maybe you need to connect to the docker socket?

The point is to get Flame dynamicly show the active services, so being able to set them that way would be awesome.
