### ISSUE TITLE
every consecutive clicked link overwrites the 2nd tab

### ISSUE THREAD

**Issue by mavgink** [pawelmalak/flame#20]
I noticed that if I for instance want to open 3 applications. The 2nd and 3rd click will always overwrite the first opened tab. Is is possible to always open a new tab? (tested in firefox and safari)

**Comment by ValentinPifu** [comment]
Yes, I encountered this problem on Firefox, Chrome. 
It'll be nice to open new tab every time.

**Comment by PossessedC0bra** [comment]
The issue is the wrong use of the target attribute. Currently the value is set to `target='blank'` which is incorrect. Instead `target='_blank'` should be used.

https://github.com/pawelmalak/flame/blob/43e110d37833366ee14d1077c623667655d7d41b/client/src/components/Apps/AppCard/AppCard.tsx#L29

https://github.com/pawelmalak/flame/blob/43e110d37833366ee14d1077c623667655d7d41b/client/src/components/Bookmarks/BookmarkCard/BookmarkCard.tsx#L14-L19
