### ISSUE TITLE
Reverse Proxy with nginx

### ISSUE THREAD

**Issue by j-archit** [pawelmalak/flame#273]
Forgive me if I sound too naive, I'm a bit new to it, but has anyone been able to setup an nginx reverse proxy to the page?

**Comment by mpalczew** [comment]
Works like any other nginx reverse proxy setup. 

```
server {
    listen 80;

    location / {
        proxy_pass http://127.0.0.1:5005;
#        allow 10.0.0.0/16;  can add some rules here about who can access the page. 
#        deny all;
    }

    server_name <your server name here>; # optional e.g. if you want a particular host to go to this. 
}
```
I added a file like the code above, called it `flame` and put it in /etc/nginx/sites-available and symlink it to /etc/nginx/sites-enabled

you may have to disable the default.

**Comment by j-archit** [comment]
I have the page on a subpath, here is the config:
```
        location ^~ /flame {
                return 301 https://$server_name/flame/;
        }

        location ^~ /flame/ {
                #rewrite /flame/(.*) /$1 break;
                proxy_http_version      1.1;
                proxy_set_header        Host            $server_name;
                proxy_set_header        Connection      $connection_upgrade;
                proxy_set_header        Host            $http_host;
                proxy_pass              http://localhost:5005;
        }
```

This gives me the following errors in the console window, and a blank white screen:
![image](https://user-images.githubusercontent.com/57045366/147980520-50d01aaf-c2d8-4622-b8ef-bfa0504b3389.png)

Any Ideas?

**Comment by KevBelisle** [comment]
It looks like Flame isn't built to support running on a "subpath", since the links to CSS and JS files are all of the form `<link rel="stylesheet" href="/flame.css">`.

To get it to work, a new feature would need to be added to allow setting the "root URL" somehow.
Seems like this is one possible solution: https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/

**Comment by pawelmalak** [comment]
Related to #106
