### ISSUE TITLE
[Feature Request] Hide URL in Applications

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [pawelmalak/flame#99]
Would be nice if I could hide these long-ass urls... https://i.imgur.com/UzuCBjm.png

**Comment by Unrepentant-Atheist** [comment]
Hm... yes,

```
.AppCard_AppCardDetails__tbAhY span {
  font-size: 0px !important;
}
```

works, still, would be better as an option in settings to hidde url.

**Comment by pawelmalak** [comment]
Not really. There are dozens of these small customization options. Someone wants to change number of columns, someone else size of greetings text or to hide some elements. It would get pretty messy if I was to implement option for every single element. That's why custom CSS functionality was added and therefore this feature won't be implemented.
